[package]

name = "rust-htslib"
version = "0.0.1"
authors = ["Christopher Schröder <christopher.schroeder@tu-dortmund.de>", "Johannes Köster <johannes.koester@tu-dortmund.de>"]
build = "build.rs"

[dev-dependencies]
tempdir = "*"
