[package]
name = "rust-htslib"
version = "0.11.0"
authors = ["Christopher Schröder <christopher.schroeder@tu-dortmund.de>", "Johannes Köster <johannes.koester@tu-dortmund.de>"]
build = "build.rs"
description = "This library provides HTSlib bindings and a high level Rust API for reading and writing BAM files."
readme = "README.md"
keywords = ["htslib", "bam", "bioinformatics", "pileup", "sequencing"]
license = "MIT"
repository = "https://github.com/rust-bio/rust-htslib.git"
documentation = "http://rust-bio.github.io/rust-htslib"


[dependencies]
libc = "0.2.*"
itertools = "0.4.*"
quick-error = "1.1.*"
newtype_derive = "0.1.*"
custom_derive = "0.1.*"
url = "1.2.*"
ieee754 = "0.1"
lazy_static = "0.1.*"
bitflags = "0.8.*"

[dev-dependencies]
tempdir = "=0.3.*"
